### PR TITLE
Add support for multiple origin servers

### PR DESCRIPTION
**Pull request by hackermd**
This PR introduces changes to the constructor of the `VolumeImageViewer` and adds the `clientMapping` option, which enables users to pass a mapping of SOP Class UIDs to DICOMweb client instances. Each client can be configured for a specific origin server and thereby make it possible to query and retrieve data from different servers, depending on the type of the data. For example, VL Whole Slide Microscopy Image, Segmentation, Comprehensive 3D SR, Microscopy Bulk Simple Annotations instances may all be stored in different archives.

### CODE REVIEW

**Review by cgorman — APPROVED** [review]
Looks good to me!

**Comment by fedorov** [comment]
I am curious, what is the reason to associate a specific DICOM SOP class with a specific server? In OHIF we implemented the functionality that allows specifying `StudyInstanceUID`, and pulling all series for that study from both the server defined in the deploy configuration, and the secondary server specified in the URL. That functionality proved extremely valuable in our radiology use case development. 

As one very typical example, one server can contain annotations by the expert, while second server can have annotations, saved using the same DICOM SOP class, produced by an automated method. I am sure there are other examples where the suggested approach will be challenged.

**Comment by hackermd** [comment]
@fedorov I agree that additional server configurations would be helpful and we don't to preclude additional future development along those lines. However, using just the SOP Class UID is very straight forward and allows us to support a large set of use cases with minimal modifications and zero overhead.

**Comment by hackermd** [comment]
I think we can elegantly extend the approach by allowing the values of `clientMapping` to be sequences of clients. The viewer can then search for data only in a specific subset of servers (instead of the full set of all servers) and retrieve data using the corresponding client.

**Pull request merged**
